FROM python:3.9-slim

WORKDIR /mlflow

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Installation des dépendances Python
COPY requirements.mlflow.txt requirements.txt
RUN pip install -r requirements.txt

# Exposition du port MLflow
EXPOSE 5000

    